# Generated by Django 4.1.2 on 2022-10-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_vps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='status',
            field=models.CharField(choices=[('started', 'Запущен'), ('blocked', 'Заблокирован'), ('stopped', 'Остановлен')], default='stopped', max_length=20, verbose_name='Статус сервера'),
        ),
    ]
